### ISSUE TITLE
内存泄漏似乎有点多啊,是不是mvp模式通病

### ISSUE THREAD

**Issue by xk21** [iceCola7/WanAndroid#11]

**Comment by iceCola7** [comment]
兄弟，能否提供一些信息，比如截图之类的，在我手机上并没有检测出来啊

**Comment by xk21** [comment]
![image](https://user-images.githubusercontent.com/22301832/44837249-b1d7fb00-ac6b-11e8-9ae6-04cd281365b1.png)

**Comment by xk21** [comment]
对象好像创建的有点多
