### ISSUE TITLE
息屏后重新亮屏导致webview重新加载页面

### ISSUE THREAD

**Issue by AaronOhO** [iceCola7/WanAndroid#13]
如题，息屏后重新亮屏导致webview重新加载页面

**Comment by iceCola7** [comment]
@Ganart 这是个问题，目前已经修改了，[点击查看](https://github.com/iceCola7/WanAndroid/commit/262481fc533eed0fb180f286e1c8e67aae2295fd)修改的代码，谢谢反馈 ^_^
