### ISSUE TITLE
mView为什么持有LifecycleOwner？

### ISSUE THREAD

**Issue by wangxp423** [iceCola7/WanAndroid#16]
`    override fun attachView(mView: V) {
        mCompositeDisposable = CompositeDisposable()
        this.mView = mView
        if (mView is LifecycleOwner) {
            (mView as LifecycleOwner).lifecycle.addObserver(this)
        }
        if (useEventBus()) {
            EventBus.getDefault().register(this)
        }
    }`

刚接触lifecycle我很好奇的是，这个地方的mView为什么会是一个LifecycleOwer呢？还请指点一下。

**Comment by iceCola7** [comment]
@wangxp423  `AppCompatActivity` 最终会继承 `SupportActivity` ，`SupportActivity` 实现了 `LifecycleOwner` 接口。

![SupportActivity](https://user-images.githubusercontent.com/20675928/46206465-a3f2c400-c356-11e8-84fc-e41822fb6857.png)
