### ISSUE TITLE
DataRepo 也就是bean类么

### ISSUE THREAD

**Issue by jasonSuzhow** [iceCola7/WanAndroid#18]
如果是的话,里面的是怎么生成的

**Comment by iceCola7** [comment]
@jasonSuzhow 是，里面的实体我都是手动写的~~，没找到别的什么方法可以生成~~！如果你找到好的方法，感谢过来分享 ^_^

**Comment by iceCola7** [comment]
@jasonSuzhow https://github.com/wuseal/JsonToKotlinClass  最近发现这个库挺好用的，可以把 json 转成 kotlin 实体类。

**Comment by jasonSuzhow** [comment]
> @jasonSuzhow https://github.com/wuseal/JsonToKotlinClass 最近发现这个库挺好用的，可以把 json 转成 kotlin 实体类。

嗯嗯, 谢谢
