### ISSUE TITLE
HomeFragment  的 置顶 条目 收藏了  刷新一下 又变回不收藏 图标 实际收藏状态

### ISSUE THREAD

**Issue by landingpencil** [iceCola7/WanAndroid#19]
HomeFragment  的 置顶 条目 收藏了  刷新一下 又变回不收藏 图标 实际收藏状态

api collect  刷新反回事 false

**Comment by iceCola7** [comment]
@landingpencil 问题已经修改了 ^_^ ，请看[这里](https://github.com/hongyangAndroid/wanandroid/issues/86)
