### ISSUE TITLE
BottomNavigationView文字显示不全

### ISSUE THREAD

**Issue by canyie** [iceCola7/WanAndroid#20]
在我没有切换到“知识体系“时显示正常，但是当我切换到“知识体系”后只能显示出“知识体”三个字
屏幕是720x1280的
因为我现在使用的是手机难以上传截图，截图请稍等

**Comment by canyie** [comment]
正常时
[![Screenshot_2018-11-22-20-13-41.png](https://i.loli.net/2018/11/22/5bf6a6211c570.png)](https://i.loli.net/2018/11/22/5bf6a6211c570.png)

**Comment by canyie** [comment]
出现问题时
[![Screenshot_2018-11-22-20-13-44.png](https://i.loli.net/2018/11/22/5bf6a67b33918.png)](https://i.loli.net/2018/11/22/5bf6a67b33918.png)

**Comment by iceCola7** [comment]
@canyie 问题已经修改了~~ 谢谢反馈！

**Comment by canyie** [comment]
好的~
