### ISSUE TITLE
数据解析问题

### ISSUE THREAD

**Issue by xianxianbuxian** [iceCola7/WanAndroid#22]
作者  想问一下我用这个项目 的网络框架 okhttp打印数据是全的 但是用到实体类 总是显示三个字段这样是有值的，其他的都是null 这是怎么回事尼。期待你的答复 谢谢

**Comment by iceCola7** [comment]
@xianxianbuxian
![image](https://user-images.githubusercontent.com/20675928/49006503-34595380-f1a4-11e8-8808-d71388939702.png)
先找到 `RetrofitHelper` 类，再找到截图上红框位置，把 `addConverterFactory(MoshiConverterFactory.create())` 注释掉，换成 `addConverterFactory(GsonConverterFactory.create())` 试一试。如果还是不行的话，麻烦把你写的实体类发来看下~，还有把 （三个字段这样是有值的，其他的都是null ）的日志截图发来吧~

**Comment by xianxianbuxian** [comment]
我自己换成GsonConverterFactory 实体类也用 gson 不用 Moshi格式就弄好了 很奇怪。Moshi格式就只解析部分。我是把你的基本框架抽出来写个项目，使用Moshi格式就这样部分为空
![ab](https://user-images.githubusercontent.com/23261279/49010838-61f7ca00-f1af-11e8-9ed6-1f9e53e48866.png)


-

**Comment by iceCola7** [comment]
好吧~~ 你写的项目准备开源吗？

**Comment by xianxianbuxian** [comment]
没 在学习Kotlin 练手做点东西

**Comment by iceCola7** [comment]
嗯嗯  加油~
