### ISSUE TITLE
亲，我用你下面的代码来切换夜间模式，为什么没反应？求指点

### ISSUE THREAD

**Issue by gaoleicoding** [iceCola7/WanAndroid#23]
public void useNightMode(boolean isNight) {
        if (isNight) {
            AppCompatDelegate.setDefaultNightMode(
                    AppCompatDelegate.MODE_NIGHT_YES);
        } else {
            AppCompatDelegate.setDefaultNightMode(
                    AppCompatDelegate.MODE_NIGHT_NO);
        }
        recreate();
    }

**Comment by iceCola7** [comment]
@gaoleicoding 项目的主题要用这个：`<style name="BaseAppTheme" parent="@style/Theme.AppCompat.DayNight"></style>`，看下你的修改了没？
