### ISSUE TITLE
更新：wanandroid 域名切换为https啦

### ISSUE THREAD

**Issue by hongyangAndroid** [iceCola7/WanAndroid#27]
为了满足小程序等开发需求，wanandroid 域名切换为https啦，需要尽快更新下 baseurl，目前可能部分http接口会异常，有问题及时反馈我，谢谢！

**Comment by iceCola7** [comment]
好的，鸿神，现在已经升级完毕，最新版本可扫描二维码下载，也可在APP内更新~~

**Comment by hongyangAndroid** [comment]
感谢，已更新体验~
