### ISSUE TITLE
最近在学习这个项目，请教一个关于 DataRepo 的问题

### ISSUE THREAD

**Issue by TuSiXiu** [iceCola7/WanAndroid#31]
`//data class HttpResult<T>(@Json(name = "data") val data: T,
//                         @Json(name = "errorCode") val errorCode: Int,
//                         @Json(name = "errorMsg") val errorMsg: String)

data class HttpResult<T>(
        @Json(name = "data") val data: T
) : BaseBean()`

为什么注释了第一种方式，而选用了第二种方式

**Comment by iceCola7** [comment]
谢谢支持~~

当时是为了构造截图中的一个方法，使用第一种方式出现了一些问题，所以才采用第二种方式了。

![image](https://user-images.githubusercontent.com/20675928/62822986-2aef0a80-bbbe-11e9-96c3-91fa4c9cc804.png)

**Comment by TuSiXiu** [comment]
感谢您的回复，谢谢
