### ISSUE TITLE
接口问题

### ISSUE THREAD

**Issue by Asmewill** [iceCola7/WanAndroid#32]

**Comment by Asmewill** [comment]
初次安装，运行你的代码，安装的dubug版本，首页进去就是数据获取失败，公众号，导航页，项目等页面都是获取失败，是接口有问题吗，麻烦您有空抽时间看下，谢谢了

**Comment by iceCola7** [comment]
谢谢反馈~~这个bug已修复，接口没有问题呢 ^_^

**Comment by Asmewill** [comment]
okak，i will try again thanks

**Comment by Asmewill** [comment]
okak，i will try again thanks
