### ISSUE TITLE
关于MVP中BaseBasePresenter中问题

### ISSUE THREAD

**Issue by sy007** [iceCola7/WanAndroid#34]
很感谢作者开源此项目，实属不易。**看了下作者写的**BasePresenter**，其中有使用**lifecycle**感知View的生命周期，但是为啥在代码中注释此代码呢？却在Activity#onDestroy中调用detachView(),是因为生命周期感知覆盖不全面吗？还是有其他坑？还请不吝赐教。
```
    @OnLifecycleEvent(Lifecycle.Event.ON_DESTROY)
    fun onDestroy(owner: LifecycleOwner) {
        // detachView()
        owner.lifecycle.removeObserver(this)
    }
```
还有一点，在**RetrofitHelper**中，看作者使用**lazy**创建**ApiService**实例， 默认情况下，对于 lazy 属性的求值是同步锁的（synchronized）， 该值只在一个线程中计算，并且所有线程会看到相同的值。而这里作者在获取getRetrofit()实例时，却synchronized了下，感觉这一步没有必要呀！

**Comment by iceCola7** [comment]
谢谢反馈~ 
1、当时这样写是因为 Lifecycle 在感知 Fragment#onDestroyView 时有点问题（出现在调用的次数上），但是我刚才又测试了一下，又没有问题了  [手动尴尬] 。不过这两种解绑 View 的方式都可以实现想要的结果。
2、这一步确实多此一举了（失误失误 ^_^ ），哈哈哈，谢谢指出~  源码已经修改了呢

最后，LZ 看的很细致了呢，很感谢能够指出项目中出现的问题，不然就误导了其他人了~   ^_^ 。
