### ISSUE TITLE
想交流一下这种夜间模式的方法的bug

### ISSUE THREAD

**Issue by mzicode** [iceCola7/WanAndroid#36]
拉下来你的项目，如果设置成夜间模式，杀死进程后，

再进入，因为保存了状态application会设置此项目是全局夜间模式。 

此时点进含有webview的文章内页，然后退出去，在部分android 9 系统（目前我所发现的miui 三星 vivo）中，首页会被刷新。 

这是一个很大的问题。希望可以讨论交流。 

不知道博主是否将此方案用到正式项目中，希望得到回复和交流

**Comment by mzicode** [comment]
因为项目中要用到夜间模式，所以我就找了大量的例子研究，

但是在application中设置全局夜间模式生效之后，然后就会重现这个bug，

不光博主的项目，网上有很多关于这个方案的demo和文章都没有提及这个问题，但是他们的demo都会出现此问题，只要含有webview。

不知道是不是真的有人把这个看起来简单了很多的方案应用于商业项目。

目前所看到的大多数app夜间模式，还在用定义两种theme，一个控件一个控件的,各种属性定义attr 的方式进行刷新。

**Comment by iceCola7** [comment]
不好意思了，回复的太晚了。。。这种夜间模式的切换暂时没有集成到商业项目中实践~
