### ISSUE TITLE
搜索出现大量重复数据

### ISSUE THREAD

**Issue by xuzongmeng** [iceCola7/WanAndroid#37]
![ea2c3daeac93960160a2980712f5146](https://user-images.githubusercontent.com/16155051/72215864-22777300-3554-11ea-8630-09a3266e06cf.jpg)
 wanAndroid账号：xzm1102207843

**Comment by iceCola7** [comment]
谢谢反馈~~~ 这是个bug，现已经修复了 ^_^  等待下个版本一起发吧

**Comment by xuzongmeng** [comment]
说好的奖励积分呢，一直没看到

**Comment by sysdl132** [comment]
@iceCola7 
![image](https://user-images.githubusercontent.com/54708046/77130296-56aa6b00-6a92-11ea-8059-88b6baf0e3ee.png)
what happened...I think you should complete them...(LICENSE)

翻译：
 APPENDIX: How to apply the Apache License to your work.

      To apply the Apache License to your work, attach the following
      boilerplate notice, with the fields enclosed by brackets "[]"
      replaced with your own identifying information. (Don't include
      the brackets!)  The text should be enclosed in the appropriate
      comment syntax for the file format. We also recommend that a
      file or class name and description of purpose be included on the
      same "printed page" as the copyright notice for easier
      identification within third-party archives.
附录：如何将Apache许可证应用于您的工作。

       要将Apache许可证应用于您的工作，请附加以下内容
       样板公告，其字段用方括号“ []”括起来
       替换为您自己的识别信息。 （不包括
       括号！）文本应放在适当的位置
       文件格式的注释语法。 我们还建议
       文件或类的名称和目的说明应包括在
       与版权声明相同的“打印页面”，更容易
       第三方档案中的标识。

**Comment by jessear** [comment]
能不能搞个能用的东西？
